server:
  port: 8888
spring:
  application:
    name: microservice-config-server
  profiles:
    active: basic

logging:
  level:
    org.springframework.cloud: DEBUG
    org.springframework.boot: DEBUG