server:
  port: 8040
spring:
  application:
    name: microservice-getway-zuul
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/
management:
  security:
    enabled: false

zuul:
  routes:
    microservice-provider-user:
      path: /user/**
      strip-prefix: false

logging:
  level:
    com.netflix: DEBUG




