server:
  port: 8011


spring:
  application:
    name: microservice-consumer-movie-feign

eureka:
  client:
    servericeUrl:
      defaultZone: http://peer1:8761/eureka/
    healthcheck:
      enabled: true
  instance:
      prefer-ip-address: true

logging:
  level:
    springcloud.service.UserFeignClient: DEBUG # 将Feign接口的日志级别设置成DEBUG，因为Feign的Logger.Level只对DEBUG作出响应。
