server:
  port: 8011


spring:
  application:
    name: microservice-consumer-movie-feign
  sleuth:
    sampler:
      percentage: 1.0
  rabbitmq:
    host: localhost
    port: 5762
    username: guest
    password: guest

eureka:
  client:
    servericeUrl:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
    healthcheck:
      enabled: true
  instance:
      prefer-ip-address: true

feign:
  hystrix:
    enabled: true #这个版本的spring cloud是默认关闭Hystrix的断路器功能

logging:
  level:
    springcloud.service.UserFeignClient: DEBUG # 将Feign接口的日志级别设置成DEBUG，因为Feign的Logger.Level只对DEBUG作出响应。
