server:
  port: 8031

spring:
  application:
    name: microservice-hystrix-turbine

eureka:
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/
  instance:
    prefer-ip-address: true
    
turbine:
  cluster-name-expression: "'default'"
  app-config-list: microservice-consumer-movie,microservice-consumer-movie-feign
  aggregator:
    cluster-config: default