server:
  port: 8010
spring:
  application:
    name: microservice-consumer-movie
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 100

eureka:
  client:
    servericeUrl:
      defaultZone: http://peer1:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true

# 配置logback
logging:
  level:
    root: INFO
    org.springframework.cloud.sleuth: DEBUG
    # org.springframework.web.servlet.DispatcherServlet: DEBUG
  config: classpath:logback.xml



